name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please fill out as many fields as you can. The more information you can provide, the better the fix will be.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: markdown
    attributes:
      value: "## Expected/Actual Behavior"
  - type: textarea
    id: what-happened-general
    attributes:
      label: What happened?
      description: What happened that prompted this bug report?
      placeholder: Describe what you see...
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-happened-expected
    attributes:
      label: Expected Behavior
      description: What behavior was expected that this bug prevented?
      placeholder: Describe how it should work...
    validations:
      required: true
  - type: textarea
    id: what-happened-actual
    attributes:
      label: Actual Behavior
      description: What behavior actually happened that is considered a bug?
      placeholder: Describe how it actually worked...
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: Reproducing the Bug
      description: What steps should be taken to reproduce the bug?
      placeholder: Describe how to find it...
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Severity"
  - type: checkboxes
    attributes:
      label: Severity and Fix Necessity
      description: How important or urgent is fixing this bug?
      options:
        - label: This is urgent
          required: false
        - label: This is important
          required: false
  - type: markdown
    attributes:
      value: "## Technical Details"
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version are you using?
      options:
        - 1.0.0 (Current)
        - 1.0.0-alpha (Next)
    validations:
      required: false
  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      description: What runtime/runner are you using?
      multiple: false
      options:
        - node
        - deno
        - bun
    validations:
      required: true
  - type: input
    id: runtime-version
    attributes:
      label: Runtime Version
      description: What version is the runtime? Find it by running `<runtime> --version`
      placeholder: ex. 16.0.0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh
  - type: markdown
    attributes:
      value: "Code of Conduct"
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
