name: Node CI

on:
  pull_request:
    branches: [main]

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
