name: Pull Request CI

on:
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run cov
      - name: Check if PR has Changeset
        run: pnpm changeset status --since=main
      - name: Run Linters
        run: pnpm run lint
