name: CI On Push

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node v16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: pnpm ci

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: pnpm run test

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Linters
        run: pnpm run lint
